server:
  port:
    9093

spring:
  cache:
    type: redis
  session:
    storage-type: redis
  redis:
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379, 127.0.0.1:26380, 127.0.0.1:26381
    host: localhost
    port: 6379